Improve lfrc
Add fuzzy find functions.
Add preview for directories.
Finalize compression function.

diff --git a/.config/lf/lfrc b/.config/lf/lfrc
--- a/.config/lf/lfrc
+++ b/.config/lf/lfrc
@@ -264,12 +264,12 @@ cmd extract %{{
     set -f
     ecmd=""
     case "$f" in
-        *.tar.bz|*.tar.bz2|*.tbz|*.tbz2) ecmd="tar xjvf '$f'";;
-        *.tar.gz|*.tgz) ecmd="tar xzvfk '$f'";; # done
-        *.tar.xz|*.txz) ecmd="tar xJvf '$f'";;
-        *.zip) ecmd="unzip -n '$f'";; # done
-        *.rar) ecmd="unrar x -inul -o- '$f'";; # done
-        *.7z) ecmd="7z x -aos '$f'";; # done
+        *.tar.bz|*.tar.bz2|*.tbz|*.tbz2) ecmd="tar xjvfk '$f'";;
+        *.tar.gz|*.tgz) ecmd="tar xzvfk '$f'";;
+        *.tar.xz|*.txz) ecmd="tar xJvfk '$f'";;
+        *.zip) ecmd="unzip -n '$f'";;
+        *.rar) ecmd="unrar x -inul -o- '$f'";;
+        *.7z) ecmd="7z x -aos '$f'";;
         *) printf "\033[48;5;196;38;5;15m[1] Unrecognized archive type\033[0m\n"; return 1;;
     esac
     if eval "$ecmd > /dev/null 2>&1"; then
@@ -279,24 +279,21 @@ cmd extract %{{
     fi
 }}
 
-# compress current file or selected files with tar and gunzip
-cmd tar ${{
-    set -f
-    mkdir $1
-    cp -r $fx $1
-    tar czf $1.tar.gz $1
-    rm -rf $1
-}}
-
 # compress current file or selected files with zip
-cmd zip ${{
-    set -f
-    mkdir $1
-    cp -r $fx $1
-    zip -r $1.zip $1
-    rm -rf $1
+cmd zip %{{
+    printf "Enter new archive name: "
+    read -r ans
+    if [ -z "$ans" ]; then printf "\033[48;5;196;38;5;15m[1] new name cannot be empty\033[0m\n"; return; fi
+    ans="${ans%.zip}"
+    # Check if a file with the same name already exists
+    if [ -e "$ans.zip" ]; then printf "\033[48;5;196;38;5;15m[1] a file already exists with name %s\033[0m\n" "$ans.zip"; return; fi
+    # Zip command ignores directory names
+    if zip -rqj "$ans.zip" "$fx"; then
+        printf "\033[48;5;34;38;5;15m[1] archive %s created\033[0m\n" "$ans.zip"
+    else
+        printf "\033[48;5;196;38;5;15m[1] archive %s could not be created\n" "$ans.zip"
+    fi
 }}
-cmd tar2 %tar cvf "$f.tar" "$f"
 
 # Make selected files executable
 cmd chmod %{{
@@ -312,11 +309,8 @@ cmd vscode %{{
 
 # Open file in Sublime
 cmd sublime %{{
-    if [ -f "$f" ]; then
-        subl "$f"
-        lf -remote 'send reload'
-    else
-        printf "\033[48;5;196;38;5;15m[1] cannot open a directory with Sublime\033[0m\n"
+    if [ -f "$f" ]; then subl "$f"; lf -remote 'send reload'
+    else printf "\033[48;5;196;38;5;15m[1] cannot open a directory with Sublime\033[0m\n"
     fi
 }}
 
@@ -342,16 +336,32 @@ cmd openfinder %{{
 cmd on-quit clear
 
 # Jump to file or dir with fzf
-cmd fzf_select ${{
-    res="$(find -L . \( -path '*/\.*' -o -fstype 'dev' -o -fstype 'proc' \) -prune -o -print 2> /dev/null | sed 1d | cut -b3- | fzf +m)"
-    if [ -d "$res" ] ; then
-        cmd="cd"
-    elif [ -f "$res" ] ; then
-        cmd="select"
-    else
-        exit 0
-    fi
-    lf -remote "send $id $cmd \"$res\""
+cmd findhere ${{
+    res="$(fd --color=always -d 1 --hidden | fzf +m --ansi -e --reverse --color "hl:-1:underline,hl+:-1:underline:reverse" || return 0)"
+    if [ -d "$res" ]; then cmd="cd"; else cmd="select"; fi
+	lf -remote "send $id $cmd \"$res\""
+}}
+
+# Find a file recursively and jump to it
+cmd findfile ${{
+    res="$(fd --color=always -d 5 --type=file --fixed-strings | 
+        fzf +m --ansi -e --reverse \
+        --color "hl:-1:underline,hl+:-1:underline:reverse" \
+        --preview-window 'right,45%,border-bottom,+{2}+3/3,~3' \
+        --preview '~/.config/lf/preview {} ${FZF_PREVIEW_COLUMNS} ${FZF_PREVIEW_LINES}' \
+        || return 0)"
+	lf -remote "send $id select \"$res\""
+}}
+
+# Find a file recursively and jump to it
+cmd finddir ${{
+    res="$(fd --color=always -d 5 --type=directory --fixed-strings | 
+        fzf +m --ansi -e --reverse \
+        --color "hl:-1:underline,hl+:-1:underline:reverse" \
+        --preview-window 'right,40%,border-bottom,+{2}+3/3,~3' \
+        --preview 'eza --icons --color=always --group-directories-first --width ${FZF_PREVIEW_COLUMNS} {}' \
+        || return 0)"
+	lf -remote "send $id cd \"$res\""
 }}
 
 # Ask AI a question on the current file
@@ -380,15 +390,20 @@ map d
 map c
 map e
 #map f
-map w
 map d
 map r
 map v
 map s
 map f
+map t
+map w
 
+map ff findfile
+map fd finddir
+map <c-f> findhere
+map J $lf -remote "send $id cd $(sed -e 's/\s*#.*//' -e '/^$/d' -e 's/^\S*\s*//' ~/.config/lf/test | fzf)"
 map <c-c> copy
-map p paste
+map p :paste; clear
 map x cut
 map i invert
 map d clear
@@ -414,17 +429,14 @@ map sbl sublime
 map cfp copyfilepath
 map cdp copydirpath
 map clone clone
-map fd openfinder
+map fm openfinder
 map . set hidden!
 map fzf fzf_select
+map zip zip
 
 # execute current file (must be executable)
-map ex $$f
-map eX !$f
-
-# dedicated keys for file opener actions
-map o &mimeopen $f
-map O $mimeopen --ask $f
+map ex ${{ zsh -ic "$f || exit 0"; lf -remote "send $id quit"}}
+map eX !{{ zsh -ic "$f || exit 0" }}
 
 # Movement
 map gh cd ~
